version: '3.8'

services:
  strapi:
    build:
      context: ./backend
    ports:
      - '1337:1337'
    volumes:
      - ./backend:/app
      - ./backend/.tmp:/app/.tmp
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
